import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/commons/footer-primary";
import { FloatingNav } from "@/components/commons/floating-navbar";
import { navigationLinks } from "@/lib/constants/navigation-items";
import HeaderMobile from "@/components/commons/header-mobile";
import WidthLayout from "@/components/commons/width-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-cover bg-top bg-no-repeat 
       `}
      >
        <WidthLayout>
          <HeaderMobile />
          <FloatingNav navItems={navigationLinks} />
        </WidthLayout>
        {children}

        <WidthLayout>
          <Footer />
        </WidthLayout>
      </body>
    </html>
  );
}
